all:
	echo "noop: all"

install:
	mkdir -p $(DESTDIR)/usr/bin
	install -m 755 ostree-ext-cli $(DESTDIR)/usr/bin

clean:
	echo "noop: clean"

distclean:
	echo "noop: distclean"

.PHONY: all install clean distclean
