name: Build python
on:
  push:
    branches:
      - main
    paths:
      - 'python/**'

  pull_request:
    paths:
      - 'python/**'

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Packagecloud?'
        required: false
        type: boolean
        default: false
      container:
        description: 'Publish container?'
        required: false
        type: boolean
        default: false
      container_tag:
        description: 'Tag for container'
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/build-packages.yml
    with:
      make: python
      platforms: linux/amd64
    secrets:
      BUILD_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  publish:
    if: (github.event_name == 'push') || (github.event.inputs.publish == 'true')
    uses: ./.github/workflows/publish-packages.yml
    with:
      platforms: linux/amd64,linux/arm64
    needs: build
    secrets:
      BUILD_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

  container:
    if: (github.event_name == 'push') || (github.event.inputs.container == 'true')
    needs: build
    uses: ./.github/workflows/publish-container.yml
    with:
      path: python
      container_name: caketop/python-build
      container_tag: ${{ github.event.inputs.container_tag }}
      buildx_args: --target python_dev
    secrets:
      BUILD_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
