name: Build ostree
on:
  push:
    branches:
      - main
    paths:
      - 'ostree/**'

  pull_request:
    paths:
      - 'ostree/**'

  # Allow for manually running
  workflow_dispatch:
#    inputs:
#      container_tag:
#        description: Tag for container
#        default: "latest"
#        required: true

jobs:
  cibuild:
    runs-on: ubuntu-20.04
    env:
      BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

    steps:
      - uses: act10ns/slack@v1.5.1
        with:
          status: starting
          channel: "#builds"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: actions/checkout@v2

      # Needed for buildx gha cache to work
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Build container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CONTAINER_TAG=$(echo "$RAW_CONTAINER_TAG" | sed 's/[^a-zA-Z0-9]\+/-/')

          cd ostree && docker buildx build \
            --platform "$BUILD_PLATFORMS" \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --pull  .

      - uses: act10ns/slack@v1.5.1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#builds"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}
        if: always()
