name: Publish packages
on:
  workflow_call:
    secrets:
      BUILD_WEBHOOK_URL:
        required: true
      PACKAGECLOUD_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Install Packagecloud CLI
        run: sudo gem install package_cloud

      - run: find artifacts \( -name '*.deb' -o -name '*.ddeb' -o -name '*.dsc' \) -print

      - name: Upload packages
        run: |
          set -x

          while IFS= read -r -d '' package ; do
            if [[ $package == *.ddeb ]]; then
              deb=$(basename $package .ddeb).deb
              mv "$package" "$deb"
              package=$deb
            fi

            package_cloud push caketop/bootleg-packages/ubuntu/focal "$package" || true
          done < <(find artifacts \( -name '*.deb' -o -name '*.ddeb' -o -name '*.dsc' \) -print0)
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: act10ns/slack@v2.0.0
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#builds"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.BUILDS_WEBHOOK_URL }}
        if: always()
